# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-21 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seckill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successkilled',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='successkilled',
            table='success_killed',
        ),
    ]
